dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 8.X.X
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 10.X.X
    condition: redis.enabled
